const constants = {
  LOGIN: "LOGIN",
  SETUP_IDENTITY: "SETUP_IDENTITY",
  CREATE_BUCKET: "CREATE_BUCKET",
  DOES_BUCKET_EXIST: "DOES_BUCKET_EXIST",
  READ_BUCKET: "READ_BUCKET",
  ADD_FILE_TO_BUCKET: "ADD_FILE_TO_BUCKET",
  LIST_BUCKET_PATH: "LIST_BUCKET_PATH",
  ADD_MEME: "ADD_MEME",
  GET_MEME_TOKEN_LIST: "GET_MEME_TOKEN_LIST",
  TITLE_CREATE_BUCKET: "TITLE_CREATE_BUCKET",
  OPEN_BACKDROP: "OPEN_BACKDROP",
};

export default constants;
